version: "3.8"

services:
  angular-app:
    container_name: angular-app 
    build:
      context: ./takra
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Angular exposed on localhost:4200
    depends_on:
      - spring-app

  spring-app:
    container_name: spring-app 
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
